### ISSUE TITLE
Может добавить VanillaFix и FoamFix?

### ISSUE THREAD

**Issue by DenisMasterHerobrine** [Derkusmars/clay-world#6]
FoamFix: https://minecraft.curseforge.com/projects/foamfix-for-minecraft?gameCategorySlug=mc-mods&projectID=278494 (уменьшает кол-во потребляемой памяти сборкой, без него кушало 4-6 гигов, стало кушать 1,5-3 гига, да и фпс может повысить)
VanillaFix: https://minecraft.curseforge.com/projects/vanillafix?gameCategorySlug=mc-mods&projectID=292785 (Защита от перезагрузки сборки после краша (просто кидает в главное меню, а не вообще закрывает майн), увеличивает фпс и ещё несколько багфиксов)

**Comment by Derkusmars** [comment]
Добавим
